import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type { SuperRunResult } from './types';
import { SuperSelfModel } from './self-model';
import { SuperRuntime } from './runtime';
import { SuperWorld } from './world';

export class SuperDreamCycle {
  private readonly world: SuperWorld;
  private readonly runtime: SuperRuntime;
  private readonly selfModel: SuperSelfModel;

  constructor(world: SuperWorld, runtime: SuperRuntime, selfModel = new SuperSelfModel(world)) {
    this.world = world;
    this.runtime = runtime;
    this.selfModel = selfModel;
  }

  async run(now = new Date()): Promise<SuperRunResult> {
    await this.world.ensure();
    const result = await this.runtime.run({
      kind: 'dream',
      input:
        'Consolidate recent memory, produce a digest, action plan, and any patch suggestions. Do not auto-apply patches.',
      source: 'dream-cycle',
      now,
    });

    const stamp = now.toISOString().replace(/[:.]/g, '-');
    const digestPath = join(this.world.paths.dreams, `${stamp}-digest.md`);
    await mkdir(this.world.paths.dreams, { recursive: true });
    await writeFile(digestPath, result.response ?? result.error ?? '', 'utf8');

    const patchPath = await this.selfModel.proposePatch({
      title: 'Dream cycle self model review',
      rationale: 'Dream cycles must leave proposed world/self changes as auditable artifacts by default.',
      patch: '# No direct patch generated by the scaffold.\n# Future LLM output should be converted to a diff here.',
      source: 'dream',
      mode: 'propose_only',
      createdAt: now.toISOString(),
    });

    return {
      ...result,
      artifacts: [...(result.artifacts ?? []), digestPath, patchPath],
    };
  }
}
