#!/usr/bin/env bash
# Synax Bench Harness — repeatable agent performance benchmarking
#
# Runs small coding tasks via `synax run` and collects pass/fail/duration metrics.
#
# Environment variables:
#   SYNAX_BENCH_MODEL          Model name (default: "local")
#   SYNAX_BENCH_BASE_URL       OpenAI-compatible base URL (default: http://localhost:8080/v1)
#   SYNAX_BENCH_API_KEY        API key (default: "not-needed")
#   SYNAX_BENCH_TASKS          Comma-separated task names, "all", or "quick" (default: "quick")
#   SYNAX_BENCH_TIMEOUT_PER_TASK  Seconds per task (default: 300)
#
# Usage:
#   npm run bench
#   scripts/bench-synax.sh
#   SYNAX_BENCH_MODEL=qwen3-gguf SYNAX_BENCH_BASE_URL=http://127.0.0.1:1234/v1 scripts/bench-synax.sh

set -euo pipefail

# ─── Resolve paths ──────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURE_SRC="$REPO_ROOT/fixtures/bench/fixture"
TASKS_DIR="$REPO_ROOT/fixtures/bench/tasks"
RESULTS_DIR="$REPO_ROOT/bench-results"

# ─── Env var defaults ───────────────────────────────
SYNAX_BENCH_MODEL="${SYNAX_BENCH_MODEL:-local}"
SYNAX_BENCH_BASE_URL="${SYNAX_BENCH_BASE_URL:-http://localhost:8080/v1}"
SYNAX_BENCH_API_KEY="${SYNAX_BENCH_API_KEY:-not-needed}"
SYNAX_BENCH_TASKS="${SYNAX_BENCH_TASKS:-quick}"
SYNAX_BENCH_TIMEOUT_PER_TASK="${SYNAX_BENCH_TIMEOUT_PER_TASK:-300}"

# ─── Task sets ──────────────────────────────────────
ALL_TASKS=(fix-typo add-comments fix-bug)
QUICK_TASKS=(fix-typo fix-bug)

if [ "$SYNAX_BENCH_TASKS" = "all" ]; then
  TASKS=("${ALL_TASKS[@]}")
elif [ "$SYNAX_BENCH_TASKS" = "quick" ]; then
  TASKS=("${QUICK_TASKS[@]}")
else
  IFS=',' read -ra TASKS <<< "$SYNAX_BENCH_TASKS"
fi

# ─── Pre-flight checks ──────────────────────────────
if [ ! -d "$FIXTURE_SRC" ]; then
  echo "[bench] ERROR: Fixture directory not found: $FIXTURE_SRC"
  exit 1
fi

if [ ! -f "$REPO_ROOT/dist/cli.js" ]; then
  echo "[bench] WARN: synax not built. Run 'npm run build' first."
  echo "[bench] Building synax..."
  (cd "$REPO_ROOT" && npm run build) || {
    echo "[bench] ERROR: Build failed. Cannot run benchmarks."
    exit 1
  }
fi

# Check if model server is reachable
MODEL_REACHABLE=false
if SYNTAX_BENCH_SKIP_CONNECTIVITY_CHECK=true; then
  # Allow skipping check for CI/dry-run
  :
else
  BASE_HOSTPORT="${SYNAX_BENCH_BASE_URL#http://}"
  BASE_HOSTPORT="${BASE_HOSTPORT#https://}"
  BASE_HOSTPORT="${BASE_HOSTPORT%%/*}"
  BASE_HOST="${BASE_HOSTPORT%:*}"
  BASE_PORT="${BASE_HOSTPORT#*:}"
  if [ "$BASE_PORT" = "$BASE_HOSTPORT" ]; then
    # No port in URL — try to infer
    if [[ "$SYNAX_BENCH_BASE_URL" == https://* ]]; then
      BASE_PORT=443
    else
      BASE_PORT=80
    fi
  fi
  if command -v nc &>/dev/null; then
    if nc -z -w 3 "$BASE_HOST" "$BASE_PORT" 2>/dev/null; then
      MODEL_REACHABLE=true
    fi
  elif command -v timeout &>/dev/null; then
    if timeout 3 bash -c "echo >/dev/tcp/$BASE_HOST/$BASE_PORT" 2>/dev/null; then
      MODEL_REACHABLE=true
    fi
  else
    # Can't check — assume reachable and let synax fail
    MODEL_REACHABLE=true
  fi
fi

# ─── Setup workspace ────────────────────────────────
mkdir -p "$RESULTS_DIR"
WORKSPACE="$RESULTS_DIR/workspace"
rm -rf "$WORKSPACE"
cp -r "$FIXTURE_SRC" "$WORKSPACE"

# Generate .synax.toml from bench env vars so synax run can find the model
cat > "$WORKSPACE/.synax.toml" <<SYNAXCONF
# Auto-generated by Synax bench harness
[provider]
kind = "openai-compatible"
base_url = "$SYNAX_BENCH_BASE_URL"
model = "$SYNAX_BENCH_MODEL"
api_key = "$SYNAX_BENCH_API_KEY"

[agent]
context_budget_tokens = 16000
max_tool_calls = 64
SYNAXCONF

echo "[bench] Workspace: $WORKSPACE"

# ─── Metadata ───────────────────────────────────────
COMMIT_SHA="$(cd "$REPO_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ─── Run benchmarks ─────────────────────────────────
declare -a RESULT_JSONS
PASSED=0
FAILED=0
SKIPPED=0
TOTAL_DURATION_MS=0

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Synax Bench"
echo "  Model:     $SYNAX_BENCH_MODEL"
echo "  Base URL:  $SYNAX_BENCH_BASE_URL"
echo "  Tasks:     ${TASKS[*]}"
echo "  Timestamp: $TIMESTAMP"
echo "  Commit:    $COMMIT_SHA"
echo "═══════════════════════════════════════════════════════════"
echo ""

for task in "${TASKS[@]}"; do
  TASK_FILE="$TASKS_DIR/$task.md"
  if [ ! -f "$TASK_FILE" ]; then
    echo "[bench] SKIP: Task file not found: $TASK_FILE"
    SKIPPED=$((SKIPPED + 1))
    RESULT_JSONS+=("$(cat <<EOF
{
  "task": "$task",
  "status": "skipped",
  "durationMs": 0,
  "toolCalls": 0,
  "modelSteps": 0,
  "terminalState": "n/a",
  "reason": "task file not found"
}
EOF
)")
    continue
  fi

  TASK_PROMPT="$(cat "$TASK_FILE")"

  if [ "$MODEL_REACHABLE" = false ]; then
    echo "[bench] SKIP: $task — model server not reachable at $SYNAX_BENCH_BASE_URL"
    SKIPPED=$((SKIPPED + 1))
    RESULT_JSONS+=("$(cat <<EOF
{
  "task": "$task",
  "status": "skipped",
  "durationMs": 0,
  "toolCalls": 0,
  "modelSteps": 0,
  "terminalState": "n/a",
  "reason": "model server not reachable"
}
EOF
)")
    continue
  fi

  echo "───────────────────────────────────────────────────────────"
  echo "[bench] Task: $task"
  echo "[bench] Prompt: $TASK_PROMPT"

  START_NS=$(date +%s%N 2>/dev/null || echo 0)

  # Run synax with a timeout
  RUN_OUT=""
  RUN_EXIT=0
  if command -v timeout &>/dev/null; then
    RUN_OUT="$(cd "$WORKSPACE" && timeout "$SYNAX_BENCH_TIMEOUT_PER_TASK" \
      node "$REPO_ROOT/dist/cli.js" run -t "$TASK_PROMPT" -y 2>&1)" || RUN_EXIT=$?
  else
    # macOS: use perl-based timeout or just run without timeout
    if command -v perl &>/dev/null; then
      RUN_OUT="$(cd "$WORKSPACE" && perl -e 'alarm shift; exec @ARGV' "$SYNAX_BENCH_TIMEOUT_PER_TASK" \
        node "$REPO_ROOT/dist/cli.js" run -t "$TASK_PROMPT" -y 2>&1)" || RUN_EXIT=$?
    else
      RUN_OUT="$(cd "$WORKSPACE" && \
        node "$REPO_ROOT/dist/cli.js" run -t "$TASK_PROMPT" -y 2>&1)" || RUN_EXIT=$?
    fi
  fi

  END_NS=$(date +%s%N 2>/dev/null || echo 0)
  if [ "$START_NS" != "0" ] && [ "$END_NS" != "0" ]; then
    DURATION_MS=$(( (END_NS - START_NS) / 1000000 ))
  else
    DURATION_MS=0
  fi
  TOTAL_DURATION_MS=$((TOTAL_DURATION_MS + DURATION_MS))

  # Parse output for metrics
  MODEL_STEPS=$(echo "$RUN_OUT" | grep -oP 'Model steps:\s*\K\d+' || echo "0")
  TOOL_CALLS=$(echo "$RUN_OUT" | grep -oP 'Tool calls:\s*\K\d+' || echo "0")
  TERMINAL_STATE="unknown"
  if echo "$RUN_OUT" | grep -q "Status: completed"; then
    TERMINAL_STATE="completed"
  elif echo "$RUN_OUT" | grep -q "Status: failed"; then
    TERMINAL_STATE="failed"
  elif echo "$RUN_OUT" | grep -q "Terminal state:"; then
    TERMINAL_STATE=$(echo "$RUN_OUT" | grep "Terminal state:" | head -1 | sed 's/.*Terminal state:\s*//')
  fi

  if [ "$RUN_EXIT" -eq 0 ] && [ "$TERMINAL_STATE" = "completed" ]; then
    STATUS="passed"
    PASSED=$((PASSED + 1))
    echo "[bench] PASS: $task (${DURATION_MS}ms, $MODEL_STEPS steps, $TOOL_CALLS tool calls)"
  elif [ "$RUN_EXIT" -eq 0 ]; then
    # synax exited 0 but terminal state isn't 'completed' — could be partial
    STATUS="failed"
    FAILED=$((FAILED + 1))
    echo "[bench] FAIL: $task (${DURATION_MS}ms, terminal: $TERMINAL_STATE)"
  elif [ "$RUN_EXIT" -eq 124 ] || [ "$RUN_EXIT" -eq 142 ]; then
    STATUS="failed"
    FAILED=$((FAILED + 1))
    TERMINAL_STATE="timeout"
    echo "[bench] FAIL: $task — timed out after ${SYNAX_BENCH_TIMEOUT_PER_TASK}s"
  else
    STATUS="failed"
    FAILED=$((FAILED + 1))
    echo "[bench] FAIL: $task (exit=$RUN_EXIT, terminal: $TERMINAL_STATE)"
  fi

  RESULT_JSONS+=("$(cat <<EOF
{
  "task": "$task",
  "status": "$STATUS",
  "durationMs": $DURATION_MS,
  "toolCalls": $TOOL_CALLS,
  "modelSteps": $MODEL_STEPS,
  "terminalState": "$TERMINAL_STATE"
}
EOF
)")
  echo ""
done

# ─── Generate reports ───────────────────────────────
mkdir -p "$RESULTS_DIR"

# JSON report
JSON_REPORT="$RESULTS_DIR/bench-$(date +%Y%m%d-%H%M%S).json"
{
  echo "{"
  echo "  \"commit\": \"$COMMIT_SHA\","
  echo "  \"timestamp\": \"$TIMESTAMP\","
  echo "  \"model\": \"$SYNAX_BENCH_MODEL\","
  echo "  \"provider\": \"$SYNAX_BENCH_BASE_URL\","
  echo "  \"results\": ["
  for i in "${!RESULT_JSONS[@]}"; do
    if [ "$i" -gt 0 ]; then
      echo ","
    fi
    echo "${RESULT_JSONS[$i]}"
  done
  echo "  ],"
  echo "  \"summary\": {"
  echo "    \"passed\": $PASSED,"
  echo "    \"failed\": $FAILED,"
  echo "    \"skipped\": $SKIPPED,"
  echo "    \"totalDurationMs\": $TOTAL_DURATION_MS"
  echo "  }"
  echo "}"
} > "$JSON_REPORT"
echo "[bench] JSON report: $JSON_REPORT"

# Markdown report
MD_REPORT="$RESULTS_DIR/bench-$(date +%Y%m%d-%H%M%S).md"
{
  echo "# Synax Bench Report"
  echo ""
  echo "| Metric | Value |"
  echo "|--------|-------|"
  echo "| Commit | \`$COMMIT_SHA\` |"
  echo "| Timestamp | $TIMESTAMP |"
  echo "| Model | $SYNAX_BENCH_MODEL |"
  echo "| Base URL | $SYNAX_BENCH_BASE_URL |"
  echo "| Total Duration | ${TOTAL_DURATION_MS}ms |"
  echo ""
  echo "## Summary"
  echo ""
  echo "| Status | Count |"
  echo "|--------|-------|"
  echo "| Passed | $PASSED |"
  echo "| Failed | $FAILED |"
  echo "| Skipped | $SKIPPED |"
  echo ""
  echo "## Results"
  echo ""
  echo "| Task | Status | Duration (ms) | Steps | Tool Calls | Terminal |"
  echo "|------|--------|---------------|-------|------------|----------|"
  for i in "${!RESULT_JSONS[@]}"; do
    task_name=$(echo "${RESULT_JSONS[$i]}" | grep -o '"task": *"[^"]*"' | sed 's/"task": *"//;s/"//')
    status=$(echo "${RESULT_JSONS[$i]}" | grep -o '"status": *"[^"]*"' | sed 's/"status": *"//;s/"//')
    duration=$(echo "${RESULT_JSONS[$i]}" | grep -o '"durationMs": *[0-9]*' | sed 's/"durationMs": *//')
    steps=$(echo "${RESULT_JSONS[$i]}" | grep -o '"modelSteps": *[0-9]*' | sed 's/"modelSteps": *//')
    tool_calls=$(echo "${RESULT_JSONS[$i]}" | grep -o '"toolCalls": *[0-9]*' | sed 's/"toolCalls": *//')
    terminal=$(echo "${RESULT_JSONS[$i]}" | grep -o '"terminalState": *"[^"]*"' | sed 's/"terminalState": *"//;s/"//')
    echo "| $task_name | $status | $duration | $steps | $tool_calls | $terminal |"
  done

  if [ "$FAILED" -gt 0 ]; then
    echo ""
    echo "## ⚠️ Failures"
    echo ""
    for i in "${!RESULT_JSONS[@]}"; do
      if echo "${RESULT_JSONS[$i]}" | grep -q '"status": "failed"'; then
        task_name=$(echo "${RESULT_JSONS[$i]}" | grep -o '"task": *"[^"]*"' | sed 's/"task": *"//;s/"//')
        echo "- **$task_name** failed"
      fi
    done
  fi
} > "$MD_REPORT"
echo "[bench] Markdown report: $MD_REPORT"

# Also write latest symlinks
cp "$JSON_REPORT" "$RESULTS_DIR/bench-latest.json"
cp "$MD_REPORT" "$RESULTS_DIR/bench-latest.md"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Bench complete"
echo "  Passed:  $PASSED"
echo "  Failed:  $FAILED"
echo "  Skipped: $SKIPPED"
echo "  Duration: ${TOTAL_DURATION_MS}ms"
echo "═══════════════════════════════════════════════════════════"

if [ "$FAILED" -gt 0 ]; then
  exit 1
fi
exit 0
